name: Post vlAURA snapshot votes to voter multisig and send to the vote relayer

on:
  workflow_dispatch:
    inputs:
      week-string:
        description: 'Week string that votes are are being posted. should be YYYY-W##'
        required: true


jobs:
  generate_fees_report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: vlAURA Voting
      env:
        ETHNODEURL: ${{ secrets.ETHNODEURL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
      run: |
        pwd
        RUN_DIR=tools/python/aura_snapshot_voting
        pip3 install -r $RUN_DIR/requirements.txt
        python3 -r $RUN_DIR/vote.py --manual true --week-string "${{ github.event.inputs.week-string }}"
    - name: Create PR
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "task: vlaura vote report"
        title: "vlaura vote report for ${{ github.event.inputs.vote-day }}"
        branch: "gha-biweekly-vlaura-votes-${{ github.event.inputs.vote-day }}"
        branch-suffix: timestamp
        delete-branch: true
        labels: "vlAURA-Vote-Report"
  # See example in run_reports_reussable for how to take the contents of a text file and drop it as a comment - could use this for the relayer link - fancy/not required.