name: Merge JSON payloads

on:
  workflow_dispatch:
    inputs:
      runWeek:
        description: "The week to run on like YYYY-W##, should match a directory in BIPs/"
        required: true

jobs:
  merge_jsons:
    runs-on: ubuntu-latest
    outputs:
      pull-request-number: ${{ steps.cpr.outputs.pull-request-number}}
      pull-request-head-sha: ${{ steps.cpr.outputs.pull-request-head-sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Restore Compiler Caches
        id: restore-compiler-caches
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.solcx
            ~/.vvm
          key: evm-compiler-caches

      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Run script with JSON files
        run: |
          pip3 install -r action-scripts/requirements-actions.txt
          python action-scripts/merge_pr_jsons.py --target BIPs/${{ github.event.inputs.runWeek }}

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Combined JSON Payloads ${{ github.event.inputs.runWeek }}"
          title: "Combined JSON payloads ${{ github.event.inputs.runWeek }}"
          reviewers: gosuto-inzasheru,xeonus
          branch: gha-payload-merge-${{ github.event.inputs.runWeek }}
          delete-branch: true
          labels: "Merged Payloads"

      - name: Clear Old Compiler Caches
        if: ${{ steps.restore-compiler-caches.outputs.cache-hit }}
        continue-on-error: true
        run: gh cache delete "evm-compiler-caches"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save EVM Compiler Caches
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.solcx
            ~/.vvm
          key: evm-compiler-caches

  run_reports:
    needs: merge_jsons
    uses: "BalancerMaxis/multisig-ops/.github/workflows/run_reports_reusable.yaml@main"
    secrets: inherit
    with:
      pr_number: ${{ needs.merge_jsons.outputs.pull-request-number }}
      checkout_ref: "gha-payload-merge-${{ github.event.inputs.runWeek }}"
