name: Poke Onchain Rewards Injectors

on:
  workflow_dispatch:
  schedule:
    - cron: "0/5 * * * *"
env:
  KEYWORDS: ${{ secrets.KEEPER_PRIVATE_WORDS }}
  DRPC_KEY: ${{ secrets.DRPC_KEY }}
  ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TOKEN }}
  FRAXSCAN_TOKEN: ${{ secrets.FRAXSCAN_TOKEN }}
  ARBISCAN_TOKEN: ${{ secrets.ARBISCAN_TOKEN }}
  GNOSISSCAN_TOKEN: ${{ secrets.GNOSISSCAN_TOKEN }}
  POLYGONSCAN_TOKEN: ${{ secrets.POLYGONSCAN_TOKEN }}
  OPTIMISMSCAN_TOKEN: ${{ secrets.OPTIMISMSCAN_TOKEN }}
  ZKEVMSCAN_TOKEN: ${{ secrets.ZKEVMSCAN_TOKEN }}
  SNOWTRACE_TOKEN: ${{ secrets.SNOWTRACE_TOKEN }}
  SNOWSCAN_TOKEN: ${{ secrets.SNOWSCAN_TOKEN }}
  BASESCAN_TOKEN: ${{ secrets.BASESCAN_TOKEN }}
jobs:
  poke_injectors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Restore Compiler Caches
        id: restore-compiler-caches
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.solcx
            ~/.vvm
          key: evm-compiler-caches

      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Poke'em
        run: |
          cd action-scripts/brownie
          pip3 install -r requirements-actions.txt
          touch .env
          brownie run scripts/pokeInjectors.py

      - name: Clear Old Compiler Caches
        if: ${{ steps.restore-compiler-caches.outputs.cache-hit }}
        continue-on-error: true
        run: gh cache delete "evm-compiler-caches"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save EVM Compiler Caches
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.solcx
            ~/.vvm
          key: evm-compiler-caches
