name: Post vlAURA snapshot votes to voter multisig and send to the vote relayer

on:
  push:
    branches:
      - main
    paths:
      - "MaxiOps/vlaura_voting/**/input/*.csv"
  workflow_dispatch:
    inputs:
      week-string:
        description: "Week string in YYYY-W## format"
        required: true
        type: string

jobs:
  post_aura_gauge_votes:
    runs-on: ubuntu-latest
    # Only run on the original repository, not on forks
    if: github.repository == 'BalancerMaxis/multisig-ops'

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Determine week-string
        id: week-string
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            WEEK_STRING="${{ github.event.inputs.week-string }}"
          else
            # Get the path of the changed CSV file
            CSV_PATH=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '/input/.*\.csv$' | head -n 1)

            if [ -z "$CSV_PATH" ]; then
              echo "No CSV file found in recent changes."
              exit 1
            fi

            echo "CSV Path: $CSV_PATH"

            YEAR=$(echo $CSV_PATH | cut -d'/' -f3)
            WEEK=$(echo $CSV_PATH | cut -d'/' -f4)
            WEEK_STRING="${YEAR}-${WEEK}"
          fi

          echo "week-string=$WEEK_STRING" >> $GITHUB_OUTPUT
          echo "Using week-string: $WEEK_STRING"

      - name: vlAURA Voting
        env:
          DRPC_KEY: ${{ secrets.DRPC_KEY }}
          KEEPER_PRIVATE_WORDS: ${{ secrets.KEEPER_PRIVATE_WORDS }}
        run: |
          pwd
          RUN_DIR=tools/python/aura_snapshot_voting
          pip3 install -r $RUN_DIR/requirements.txt
          echo "grabbing votes for: ${{ steps.week-string.outputs.week-string }}"
          python3 $RUN_DIR/vote.py --week-string "${{ steps.week-string.outputs.week-string }}"

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "task: vlaura vote report for ${{ steps.week-string.outputs.week-string }}"
          title: "vlaura vote report for ${{ steps.week-string.outputs.week-string }}"
          branch: "gha-biweekly-vlaura-votes-${{ steps.week-string.outputs.week-string }}"
          delete-branch: true
          labels: "vlAURA-Voting-Round"
