name: Query all Chainlink upkeeps

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  query_upkeeps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "upkeeps"

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Query Dune
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
        run: |
          cd tools/python
          pip install -r requirements.txt
          python query_upkeeps.py

      - name: Commit CSV file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: "upkeeps"
          file_pattern: "upkeeps.csv"
          commit_message: "ci: dump csv file with all queried upkeeps"
