name: V3 Fee Bot
on:
  workflow_dispatch:

jobs:
  v3_fee_bot:
    runs-on: ubuntu-latest
    environment: v3-fee-bot
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: v3-fee-bot-cron

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Run bot
        env:
          DRPC_KEY: ${{ secrets.DRPC_KEY }}
          GRAPH_API_KEY: ${{ secrets.GRAPH_API_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          pip install --upgrade pip
          pip install -r action-scripts/requirements-actions.txt
          python action-scripts/v3_fee_bot.py

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Unstuck burner orders payloads"
          commit-message: "chore: add unstuck burner orders payloads"
          reviewers: gosuto-inzasheru,xeonus
          branch: gha-unstuck-burner-orders
          delete-branch: true
